import { describe, expect, it } from 'vitest'

import { buildConversationMutationPlan, buildConversationTruncatePlan } from './conversationMutationService'
import type { CharacterMemory, ConversationStateHistory, Message, PromptDebugTrace } from '../../types/domain'

const now = '2026-09-01T00:00:00.000Z'
const affectedCreatedAt = '2026-08-31T20:00:00.000Z'

function memory(overrides: Partial<CharacterMemory>): CharacterMemory {
  return {
    id: crypto.randomUUID(),
    conversationId: 'conv-1',
    characterId: 'char-1',
    category: 'event',
    content: 'memory',
    importance: 3,
    sourceType: 'automatic',
    createdAt: '2026-08-31T20:01:00.000Z',
    updatedAt: '2026-08-31T20:01:00.000Z',
    ...overrides
  }
}

function history(overrides: Partial<ConversationStateHistory>): ConversationStateHistory {
  return {
    id: crypto.randomUUID(),
    conversationId: 'conv-1',
    characterId: 'char-1',
    field: 'location',
    label: '地点变化',
    nextValue: '咖啡店',
    createdAt: '2026-08-31T20:02:00.000Z',
    ...overrides
  }
}

function message(overrides: Partial<Message>): Message {
  return {
    id: crypto.randomUUID(),
    worldId: 'world-1',
    conversationId: 'conv-1',
    senderId: 'user',
    type: 'text',
    content: 'hello',
    status: 'delivered',
    createdAt: '2026-08-31T20:00:00.000Z',
    ...overrides
  }
}

describe('buildConversationMutationPlan', () => {
  it('deletes automatic memories created from a removed message', () => {
    const row = memory({ id: 'mem-auto', sourceMessageId: 'msg-1' })
    const plan = buildConversationMutationPlan({
      affectedMessageIds: ['msg-1'],
      affectedCreatedAt,
      memories: [row],
      stateHistory: [],
      messages: [],
      now
    })

    expect(plan.automaticMemoryIdsToDelete).toEqual(['mem-auto'])
    expect(plan.automaticMemoryPatches).toEqual([])
  })

  it('never deletes manual or imported memories', () => {
    const manual = memory({ id: 'mem-manual', sourceType: 'manual', sourceMessageId: 'msg-1' })
    const imported = memory({ id: 'mem-imported', sourceType: 'imported', sourceMessageId: 'msg-1' })
    const plan = buildConversationMutationPlan({
      affectedMessageIds: ['msg-1'],
      affectedCreatedAt,
      memories: [manual, imported],
      stateHistory: [],
      messages: [],
      now
    })

    expect(plan.automaticMemoryIdsToDelete).toEqual([])
    expect(plan.automaticMemoryPatches).toEqual([])
  })

  it('detaches an older merged automatic memory instead of deleting it', () => {
    const older = memory({
      id: 'mem-old',
      sourceMessageId: 'msg-1',
      mergedFrom: ['msg-old', 'msg-1'],
      createdAt: '2026-08-30T09:00:00.000Z'
    })
    const plan = buildConversationMutationPlan({
      affectedMessageIds: ['msg-1'],
      affectedCreatedAt,
      memories: [older],
      stateHistory: [],
      messages: [],
      now
    })

    expect(plan.automaticMemoryIdsToDelete).toEqual([])
    expect(plan.automaticMemoryPatches).toEqual([{
      id: 'mem-old',
      sourceMessageId: undefined,
      mergedFrom: ['msg-old'],
      updatedAt: now
    }])
  })

  it('removes deleted message ids from mergedFrom even when the main source remains', () => {
    const merged = memory({
      id: 'mem-merged',
      sourceMessageId: 'msg-still-valid',
      mergedFrom: ['msg-still-valid', 'msg-1']
    })
    const plan = buildConversationMutationPlan({
      affectedMessageIds: ['msg-1'],
      affectedCreatedAt,
      memories: [merged],
      stateHistory: [],
      messages: [],
      now
    })

    expect(plan.automaticMemoryIdsToDelete).toEqual([])
    expect(plan.automaticMemoryPatches).toEqual([{
      id: 'mem-merged',
      mergedFrom: ['msg-still-valid'],
      updatedAt: now
    }])
  })

  it('removes state history generated by the deleted message', () => {
    const rows = [
      history({ id: 'history-remove', sourceMessageId: 'msg-1' }),
      history({ id: 'history-keep', sourceMessageId: 'msg-2' })
    ]
    const plan = buildConversationMutationPlan({
      affectedMessageIds: ['msg-1'],
      affectedCreatedAt,
      memories: [],
      stateHistory: rows,
      messages: [],
      now
    })

    expect(plan.stateHistoryIdsToDelete).toEqual(['history-remove'])
  })

  it('clears quote references that point to deleted messages', () => {
    const rows = [
      message({ id: 'msg-1' }),
      message({ id: 'msg-2', replyTo: { messageId: 'msg-1', senderName: '你', preview: 'hello', type: 'text' } }),
      message({ id: 'msg-3', replyTo: { messageId: 'msg-other', senderName: 'AI', preview: 'ok', type: 'text' } })
    ]
    const plan = buildConversationMutationPlan({
      affectedMessageIds: ['msg-1'],
      affectedCreatedAt,
      memories: [],
      stateHistory: [],
      messages: rows,
      now
    })

    expect(plan.replyReferenceMessageIdsToClear).toEqual(['msg-2'])
  })
})


describe('buildConversationTruncatePlan', () => {
  it('keeps the anchor message but invalidates its old derived runtime and all descendants', () => {
    const anchor = message({ id: 'msg-anchor', createdAt: affectedCreatedAt })
    const child = message({ id: 'msg-child', senderId: 'char-1', createdAt: '2026-08-31T20:01:00.000Z' })
    const manual = memory({ id: 'mem-manual', sourceType: 'manual', sourceMessageId: 'msg-anchor' })
    const autoAnchor = memory({ id: 'mem-anchor', sourceMessageId: 'msg-anchor' })
    const autoChild = memory({ id: 'mem-child', sourceMessageId: 'msg-child', createdAt: '2026-08-31T20:02:00.000Z' })
    const traces = [
      { id: 'debug-old', createdAt: '2026-08-31T19:59:00.000Z' },
      { id: 'debug-new', createdAt: '2026-08-31T20:00:01.000Z' }
    ] as PromptDebugTrace[]

    const plan = buildConversationTruncatePlan({
      anchorMessageId: 'msg-anchor',
      messages: [anchor, child],
      memories: [manual, autoAnchor, autoChild],
      stateHistory: [
        history({ id: 'history-anchor', sourceMessageId: 'msg-anchor' }),
        history({ id: 'history-unbound-future', sourceMessageId: undefined, createdAt: '2026-08-31T20:03:00.000Z' })
      ],
      promptDebugTraces: traces,
      now
    })

    expect(plan.removedMessageIds).toEqual(['msg-child'])
    expect(plan.automaticMemoryIdsToDelete.sort()).toEqual(['mem-anchor', 'mem-child'])
    expect(plan.automaticMemoryIdsToDelete).not.toContain('mem-manual')
    expect(plan.stateHistoryIdsToDelete.sort()).toEqual(['history-anchor', 'history-unbound-future'])
    expect(plan.promptDebugTraceIdsToDelete).toEqual(['debug-new'])
  })
})
