<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import PhoneFrame from '../components/PhoneFrame.vue'
import { clearPromptDebugTraces, listPromptDebugTraces } from '../services/promptDebugService'
import type { PromptDebugTrace } from '../types/domain'
const route=useRoute();const conversationId=computed(()=>String(route.params.id||''));const traces=ref<PromptDebugTrace[]>([]);const selectedId=ref('');const notice=ref('');const selected=computed(()=>traces.value.find(item=>item.id===selectedId.value)||traces.value[0])
async function load(){traces.value=await listPromptDebugTraces(conversationId.value);if(!selectedId.value||!traces.value.some(item=>item.id===selectedId.value))selectedId.value=traces.value[0]?.id||''}
async function copy(value:string,label:string){await navigator.clipboard.writeText(value);notice.value=`${label}已复制。`;window.setTimeout(()=>{notice.value=''},2200)}
async function clearAll(){if(!window.confirm('清除当前聊天的全部 Prompt 调试记录吗？'))return;await clearPromptDebugTraces(conversationId.value);await load()}
function formatTime(value:string){return new Date(value).toLocaleString('zh-CN',{hour12:false})}
onMounted(load);watch(conversationId,load)
</script>
<template><PhoneFrame title="Prompt 调试器" show-back><main class="debug-page"><p v-if="notice" class="notice">{{notice}}</p><section class="intro-card"><b>本地调试记录</b><p>检查角色卡、Persona、世界书、记忆和最终提示词是否正确进入本轮请求。记录不会随数据备份导出。</p></section><template v-if="selected"><label class="trace-picker"><span>选择请求</span><select v-model="selectedId"><option v-for="trace in traces" :key="trace.id" :value="trace.id">{{formatTime(trace.createdAt)}} · {{trace.model}}</option></select></label><section class="summary-grid"><article><small>角色模式</small><b>{{selected.roleplayMode}}</b></article><article><small>Persona</small><b>{{selected.personaName}}</b></article><article><small>模型</small><b>{{selected.model}}</b></article><article><small>上下文字符</small><b>{{selected.estimatedCharacters}}</b></article><article><small>世界书</small><b>{{selected.activatedLorebook.length}} 条</b></article><article><small>记忆命中</small><b>{{selected.memoryHits.length}} 条</b></article></section><details open class="debug-section"><summary>本轮诊断</summary><p><b>互动动作：</b>{{selected.actionSummary||'尚未收到完整回复'}}</p><p><b>图片：</b>{{selected.imageCount}} 张</p><p><b>互动协议：</b>{{selected.protocolEnabled?'已启用':'未启用'}}</p><div v-if="selected.naturalnessWarnings?.length" class="warnings"><b>自然度提醒</b><span v-for="warning in selected.naturalnessWarnings" :key="warning">{{warning}}</span></div><p v-else class="ok">没有命中已知 AI 腔规则。</p></details><details open class="debug-section"><summary>触发的世界书</summary><div v-if="selected.activatedLorebook.length" class="chips"><span v-for="entry in selected.activatedLorebook" :key="entry.id">{{entry.title}}</span></div><p v-else class="empty">本轮没有触发世界书。</p></details><details open class="debug-section"><summary>命中的记忆</summary><article v-for="memory in selected.memoryHits" :key="memory.id" class="memory-row"><small>重要度 {{memory.importance}}</small><p>{{memory.content}}</p></article><p v-if="!selected.memoryHits.length" class="empty">本轮没有注入长期记忆。</p></details><details class="debug-section"><summary>最终 System Prompt</summary><button type="button" @click="copy(selected.systemPrompt,'System Prompt')">复制</button><pre>{{selected.systemPrompt}}</pre></details><details class="debug-section"><summary>最近聊天上下文</summary><article v-for="(message,index) in selected.recentMessages" :key="index" class="prompt-message"><b>{{message.role}}</b><pre>{{message.content}}</pre></article></details><details v-if="selected.rawOutput" class="debug-section"><summary>模型原始输出</summary><button type="button" @click="copy(selected.rawOutput||'','原始输出')">复制</button><pre>{{selected.rawOutput}}</pre></details><details v-if="selected.visibleOutput" class="debug-section"><summary>用户实际看到的回复</summary><pre>{{selected.visibleOutput}}</pre></details><button class="clear-button" type="button" @click="clearAll">清除调试记录</button></template><p v-else class="empty-page">还没有调试记录。回到聊天发送一条消息后再查看。</p></main></PhoneFrame></template>
<style scoped>.debug-page{min-height:100%;padding:14px 14px 36px;background:#f7f0f3;color:#5d4350}.notice{position:sticky;top:6px;z-index:3;margin:0 0 10px;padding:9px 12px;border-radius:12px;background:#744f60;color:#fff;text-align:center}.intro-card,.debug-section,.trace-picker{margin-bottom:11px;border:1px solid rgba(92,58,73,.08);border-radius:18px;background:#fff;padding:14px;box-shadow:0 8px 24px rgba(75,44,58,.05)}.intro-card p{margin:7px 0 0;color:#917482;font-size:12px;line-height:1.6}.trace-picker{display:flex;align-items:center;justify-content:space-between;gap:12px}.trace-picker select{min-width:0;max-width:70%;border:1px solid #eadce2;border-radius:11px;background:#fff;padding:9px}.summary-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-bottom:11px}.summary-grid article{display:grid;gap:3px;border-radius:14px;background:#fff;padding:12px}.summary-grid small{color:#a17f8e}.summary-grid b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.debug-section summary{cursor:pointer;font-weight:800}.debug-section>button{float:right;margin-top:-25px;border:0;border-radius:10px;background:#f2e5eb;color:#9b5a75;padding:6px 10px}.debug-section pre{overflow:auto;max-height:420px;margin:12px 0 0;border-radius:12px;background:#2b2327;color:#f6eaf0;padding:12px;font:11px/1.65 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;word-break:break-word}.chips{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}.chips span{border-radius:999px;background:#f4e8ed;color:#a55e7c;padding:6px 9px;font-size:11px}.memory-row,.prompt-message{margin-top:9px;border-radius:12px;background:#f8f0f3;padding:10px}.memory-row small{color:#a27a8c}.memory-row p{margin:4px 0 0;line-height:1.55}.prompt-message pre{max-height:220px;margin-top:7px}.warnings{display:grid;gap:6px;margin-top:10px;border-radius:12px;background:#fff1e7;color:#925d2f;padding:10px}.warnings span:before{content:'· ';font-weight:900}.ok{color:#4f8065}.empty,.empty-page{color:#9a7d8a;text-align:center;line-height:1.6}.empty-page{padding:70px 20px}.clear-button{width:100%;border:0;border-radius:14px;background:#fff0f2;color:#b24d67;padding:12px;font-weight:800}</style>
